// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sqlr

import (
	"time"

	"github.com/gosoline-project/sqlr"
	mock "github.com/stretchr/testify/mock"
)

// NewEntitier creates a new instance of Entitier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEntitier[K sqlr.KeyTypes](t interface {
	mock.TestingT
	Cleanup(func())
}) *Entitier[K] {
	mock := &Entitier[K]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Entitier is an autogenerated mock type for the Entitier type
type Entitier[K sqlr.KeyTypes] struct {
	mock.Mock
}

type Entitier_Expecter[K sqlr.KeyTypes] struct {
	mock *mock.Mock
}

func (_m *Entitier[K]) EXPECT() *Entitier_Expecter[K] {
	return &Entitier_Expecter[K]{mock: &_m.Mock}
}

// GetCreatedAt provides a mock function for the type Entitier
func (_mock *Entitier[K]) GetCreatedAt() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCreatedAt")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// Entitier_GetCreatedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCreatedAt'
type Entitier_GetCreatedAt_Call[K sqlr.KeyTypes] struct {
	*mock.Call
}

// GetCreatedAt is a helper method to define mock.On call
func (_e *Entitier_Expecter[K]) GetCreatedAt() *Entitier_GetCreatedAt_Call[K] {
	return &Entitier_GetCreatedAt_Call[K]{Call: _e.mock.On("GetCreatedAt")}
}

func (_c *Entitier_GetCreatedAt_Call[K]) Run(run func()) *Entitier_GetCreatedAt_Call[K] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Entitier_GetCreatedAt_Call[K]) Return(time1 time.Time) *Entitier_GetCreatedAt_Call[K] {
	_c.Call.Return(time1)
	return _c
}

func (_c *Entitier_GetCreatedAt_Call[K]) RunAndReturn(run func() time.Time) *Entitier_GetCreatedAt_Call[K] {
	_c.Call.Return(run)
	return _c
}

// GetId provides a mock function for the type Entitier
func (_mock *Entitier[K]) GetId() K {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetId")
	}

	var r0 K
	if returnFunc, ok := ret.Get(0).(func() K); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(K)
		}
	}
	return r0
}

// Entitier_GetId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetId'
type Entitier_GetId_Call[K sqlr.KeyTypes] struct {
	*mock.Call
}

// GetId is a helper method to define mock.On call
func (_e *Entitier_Expecter[K]) GetId() *Entitier_GetId_Call[K] {
	return &Entitier_GetId_Call[K]{Call: _e.mock.On("GetId")}
}

func (_c *Entitier_GetId_Call[K]) Run(run func()) *Entitier_GetId_Call[K] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Entitier_GetId_Call[K]) Return(v K) *Entitier_GetId_Call[K] {
	_c.Call.Return(v)
	return _c
}

func (_c *Entitier_GetId_Call[K]) RunAndReturn(run func() K) *Entitier_GetId_Call[K] {
	_c.Call.Return(run)
	return _c
}

// GetUpdatedAt provides a mock function for the type Entitier
func (_mock *Entitier[K]) GetUpdatedAt() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUpdatedAt")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// Entitier_GetUpdatedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUpdatedAt'
type Entitier_GetUpdatedAt_Call[K sqlr.KeyTypes] struct {
	*mock.Call
}

// GetUpdatedAt is a helper method to define mock.On call
func (_e *Entitier_Expecter[K]) GetUpdatedAt() *Entitier_GetUpdatedAt_Call[K] {
	return &Entitier_GetUpdatedAt_Call[K]{Call: _e.mock.On("GetUpdatedAt")}
}

func (_c *Entitier_GetUpdatedAt_Call[K]) Run(run func()) *Entitier_GetUpdatedAt_Call[K] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Entitier_GetUpdatedAt_Call[K]) Return(time1 time.Time) *Entitier_GetUpdatedAt_Call[K] {
	_c.Call.Return(time1)
	return _c
}

func (_c *Entitier_GetUpdatedAt_Call[K]) RunAndReturn(run func() time.Time) *Entitier_GetUpdatedAt_Call[K] {
	_c.Call.Return(run)
	return _c
}
