// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sqlr

import (
	mock "github.com/stretchr/testify/mock"
)

// NewKeyTypes creates a new instance of KeyTypes. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKeyTypes(t interface {
	mock.TestingT
	Cleanup(func())
}) *KeyTypes {
	mock := &KeyTypes{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// KeyTypes is an autogenerated mock type for the KeyTypes type
type KeyTypes struct {
	mock.Mock
}

type KeyTypes_Expecter struct {
	mock *mock.Mock
}

func (_m *KeyTypes) EXPECT() *KeyTypes_Expecter {
	return &KeyTypes_Expecter{mock: &_m.Mock}
}
