// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sqlr

import (
	"github.com/gosoline-project/sqlr"
	mock "github.com/stretchr/testify/mock"
)

// newMutationPreloadAware creates a new instance of mutationPreloadAware. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMutationPreloadAware(t interface {
	mock.TestingT
	Cleanup(func())
}) *mutationPreloadAware {
	mock := &mutationPreloadAware{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mutationPreloadAware is an autogenerated mock type for the mutationPreloadAware type
type mutationPreloadAware struct {
	mock.Mock
}

type mutationPreloadAware_Expecter struct {
	mock *mock.Mock
}

func (_m *mutationPreloadAware) EXPECT() *mutationPreloadAware_Expecter {
	return &mutationPreloadAware_Expecter{mock: &_m.Mock}
}

// hasPreloads provides a mock function for the type mutationPreloadAware
func (_mock *mutationPreloadAware) hasPreloads() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for hasPreloads")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// mutationPreloadAware_hasPreloads_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'hasPreloads'
type mutationPreloadAware_hasPreloads_Call struct {
	*mock.Call
}

// hasPreloads is a helper method to define mock.On call
func (_e *mutationPreloadAware_Expecter) hasPreloads() *mutationPreloadAware_hasPreloads_Call {
	return &mutationPreloadAware_hasPreloads_Call{Call: _e.mock.On("hasPreloads")}
}

func (_c *mutationPreloadAware_hasPreloads_Call) Run(run func()) *mutationPreloadAware_hasPreloads_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mutationPreloadAware_hasPreloads_Call) Return(b bool) *mutationPreloadAware_hasPreloads_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *mutationPreloadAware_hasPreloads_Call) RunAndReturn(run func() bool) *mutationPreloadAware_hasPreloads_Call {
	_c.Call.Return(run)
	return _c
}

// toQueryBuilderRead provides a mock function for the type mutationPreloadAware
func (_mock *mutationPreloadAware) toQueryBuilderRead() *sqlr.QueryBuilderRead {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for toQueryBuilderRead")
	}

	var r0 *sqlr.QueryBuilderRead
	if returnFunc, ok := ret.Get(0).(func() *sqlr.QueryBuilderRead); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlr.QueryBuilderRead)
		}
	}
	return r0
}

// mutationPreloadAware_toQueryBuilderRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'toQueryBuilderRead'
type mutationPreloadAware_toQueryBuilderRead_Call struct {
	*mock.Call
}

// toQueryBuilderRead is a helper method to define mock.On call
func (_e *mutationPreloadAware_Expecter) toQueryBuilderRead() *mutationPreloadAware_toQueryBuilderRead_Call {
	return &mutationPreloadAware_toQueryBuilderRead_Call{Call: _e.mock.On("toQueryBuilderRead")}
}

func (_c *mutationPreloadAware_toQueryBuilderRead_Call) Run(run func()) *mutationPreloadAware_toQueryBuilderRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mutationPreloadAware_toQueryBuilderRead_Call) Return(queryBuilderRead *sqlr.QueryBuilderRead) *mutationPreloadAware_toQueryBuilderRead_Call {
	_c.Call.Return(queryBuilderRead)
	return _c
}

func (_c *mutationPreloadAware_toQueryBuilderRead_Call) RunAndReturn(run func() *sqlr.QueryBuilderRead) *mutationPreloadAware_toQueryBuilderRead_Call {
	_c.Call.Return(run)
	return _c
}
