// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sqlr

import (
	"github.com/gosoline-project/sqlr"
	mock "github.com/stretchr/testify/mock"
)

// NewRepositoryTx creates a new instance of RepositoryTx. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepositoryTx[K sqlr.KeyTypes, E sqlr.Entitier[K]](t interface {
	mock.TestingT
	Cleanup(func())
}) *RepositoryTx[K, E] {
	mock := &RepositoryTx[K, E]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RepositoryTx is an autogenerated mock type for the RepositoryTx type
type RepositoryTx[K sqlr.KeyTypes, E sqlr.Entitier[K]] struct {
	mock.Mock
}

type RepositoryTx_Expecter[K sqlr.KeyTypes, E sqlr.Entitier[K]] struct {
	mock *mock.Mock
}

func (_m *RepositoryTx[K, E]) EXPECT() *RepositoryTx_Expecter[K, E] {
	return &RepositoryTx_Expecter[K, E]{mock: &_m.Mock}
}

// Close provides a mock function for the type RepositoryTx
func (_mock *RepositoryTx[K, E]) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RepositoryTx_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type RepositoryTx_Close_Call[K sqlr.KeyTypes, E sqlr.Entitier[K]] struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *RepositoryTx_Expecter[K, E]) Close() *RepositoryTx_Close_Call[K, E] {
	return &RepositoryTx_Close_Call[K, E]{Call: _e.mock.On("Close")}
}

func (_c *RepositoryTx_Close_Call[K, E]) Run(run func()) *RepositoryTx_Close_Call[K, E] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RepositoryTx_Close_Call[K, E]) Return(err error) *RepositoryTx_Close_Call[K, E] {
	_c.Call.Return(err)
	return _c
}

func (_c *RepositoryTx_Close_Call[K, E]) RunAndReturn(run func() error) *RepositoryTx_Close_Call[K, E] {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type RepositoryTx
func (_mock *RepositoryTx[K, E]) Create(ttx sqlr.TTx, entity *E, opts ...func(qb *sqlr.QueryBuilderCreate)) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ttx, entity, opts)
	} else {
		tmpRet = _mock.Called(ttx, entity)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(sqlr.TTx, *E, ...func(qb *sqlr.QueryBuilderCreate)) error); ok {
		r0 = returnFunc(ttx, entity, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RepositoryTx_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type RepositoryTx_Create_Call[K sqlr.KeyTypes, E sqlr.Entitier[K]] struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ttx sqlr.TTx
//   - entity *E
//   - opts ...func(qb *sqlr.QueryBuilderCreate)
func (_e *RepositoryTx_Expecter[K, E]) Create(ttx interface{}, entity interface{}, opts ...interface{}) *RepositoryTx_Create_Call[K, E] {
	return &RepositoryTx_Create_Call[K, E]{Call: _e.mock.On("Create",
		append([]interface{}{ttx, entity}, opts...)...)}
}

func (_c *RepositoryTx_Create_Call[K, E]) Run(run func(ttx sqlr.TTx, entity *E, opts ...func(qb *sqlr.QueryBuilderCreate))) *RepositoryTx_Create_Call[K, E] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 sqlr.TTx
		if args[0] != nil {
			arg0 = args[0].(sqlr.TTx)
		}
		var arg1 *E
		if args[1] != nil {
			arg1 = args[1].(*E)
		}
		var arg2 []func(qb *sqlr.QueryBuilderCreate)
		var variadicArgs []func(qb *sqlr.QueryBuilderCreate)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(qb *sqlr.QueryBuilderCreate))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *RepositoryTx_Create_Call[K, E]) Return(err error) *RepositoryTx_Create_Call[K, E] {
	_c.Call.Return(err)
	return _c
}

func (_c *RepositoryTx_Create_Call[K, E]) RunAndReturn(run func(ttx sqlr.TTx, entity *E, opts ...func(qb *sqlr.QueryBuilderCreate)) error) *RepositoryTx_Create_Call[K, E] {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type RepositoryTx
func (_mock *RepositoryTx[K, E]) Delete(ttx sqlr.TTx, id K, opts ...func(qb *sqlr.QueryBuilderDelete)) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ttx, id, opts)
	} else {
		tmpRet = _mock.Called(ttx, id)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(sqlr.TTx, K, ...func(qb *sqlr.QueryBuilderDelete)) error); ok {
		r0 = returnFunc(ttx, id, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RepositoryTx_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type RepositoryTx_Delete_Call[K sqlr.KeyTypes, E sqlr.Entitier[K]] struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ttx sqlr.TTx
//   - id K
//   - opts ...func(qb *sqlr.QueryBuilderDelete)
func (_e *RepositoryTx_Expecter[K, E]) Delete(ttx interface{}, id interface{}, opts ...interface{}) *RepositoryTx_Delete_Call[K, E] {
	return &RepositoryTx_Delete_Call[K, E]{Call: _e.mock.On("Delete",
		append([]interface{}{ttx, id}, opts...)...)}
}

func (_c *RepositoryTx_Delete_Call[K, E]) Run(run func(ttx sqlr.TTx, id K, opts ...func(qb *sqlr.QueryBuilderDelete))) *RepositoryTx_Delete_Call[K, E] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 sqlr.TTx
		if args[0] != nil {
			arg0 = args[0].(sqlr.TTx)
		}
		var arg1 K
		if args[1] != nil {
			arg1 = args[1].(K)
		}
		var arg2 []func(qb *sqlr.QueryBuilderDelete)
		var variadicArgs []func(qb *sqlr.QueryBuilderDelete)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(qb *sqlr.QueryBuilderDelete))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *RepositoryTx_Delete_Call[K, E]) Return(err error) *RepositoryTx_Delete_Call[K, E] {
	_c.Call.Return(err)
	return _c
}

func (_c *RepositoryTx_Delete_Call[K, E]) RunAndReturn(run func(ttx sqlr.TTx, id K, opts ...func(qb *sqlr.QueryBuilderDelete)) error) *RepositoryTx_Delete_Call[K, E] {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type RepositoryTx
func (_mock *RepositoryTx[K, E]) Query(ttx sqlr.TTx, opts ...func(qb *sqlr.QueryBuilderSelect)) ([]E, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ttx, opts)
	} else {
		tmpRet = _mock.Called(ttx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 []E
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(sqlr.TTx, ...func(qb *sqlr.QueryBuilderSelect)) ([]E, error)); ok {
		return returnFunc(ttx, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(sqlr.TTx, ...func(qb *sqlr.QueryBuilderSelect)) []E); ok {
		r0 = returnFunc(ttx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]E)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(sqlr.TTx, ...func(qb *sqlr.QueryBuilderSelect)) error); ok {
		r1 = returnFunc(ttx, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RepositoryTx_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type RepositoryTx_Query_Call[K sqlr.KeyTypes, E sqlr.Entitier[K]] struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ttx sqlr.TTx
//   - opts ...func(qb *sqlr.QueryBuilderSelect)
func (_e *RepositoryTx_Expecter[K, E]) Query(ttx interface{}, opts ...interface{}) *RepositoryTx_Query_Call[K, E] {
	return &RepositoryTx_Query_Call[K, E]{Call: _e.mock.On("Query",
		append([]interface{}{ttx}, opts...)...)}
}

func (_c *RepositoryTx_Query_Call[K, E]) Run(run func(ttx sqlr.TTx, opts ...func(qb *sqlr.QueryBuilderSelect))) *RepositoryTx_Query_Call[K, E] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 sqlr.TTx
		if args[0] != nil {
			arg0 = args[0].(sqlr.TTx)
		}
		var arg1 []func(qb *sqlr.QueryBuilderSelect)
		var variadicArgs []func(qb *sqlr.QueryBuilderSelect)
		if len(args) > 1 {
			variadicArgs = args[1].([]func(qb *sqlr.QueryBuilderSelect))
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *RepositoryTx_Query_Call[K, E]) Return(vs []E, err error) *RepositoryTx_Query_Call[K, E] {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *RepositoryTx_Query_Call[K, E]) RunAndReturn(run func(ttx sqlr.TTx, opts ...func(qb *sqlr.QueryBuilderSelect)) ([]E, error)) *RepositoryTx_Query_Call[K, E] {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type RepositoryTx
func (_mock *RepositoryTx[K, E]) Read(ttx sqlr.TTx, id K, opts ...func(qb *sqlr.QueryBuilderRead)) (*E, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ttx, id, opts)
	} else {
		tmpRet = _mock.Called(ttx, id)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 *E
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(sqlr.TTx, K, ...func(qb *sqlr.QueryBuilderRead)) (*E, error)); ok {
		return returnFunc(ttx, id, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(sqlr.TTx, K, ...func(qb *sqlr.QueryBuilderRead)) *E); ok {
		r0 = returnFunc(ttx, id, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*E)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(sqlr.TTx, K, ...func(qb *sqlr.QueryBuilderRead)) error); ok {
		r1 = returnFunc(ttx, id, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RepositoryTx_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type RepositoryTx_Read_Call[K sqlr.KeyTypes, E sqlr.Entitier[K]] struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ttx sqlr.TTx
//   - id K
//   - opts ...func(qb *sqlr.QueryBuilderRead)
func (_e *RepositoryTx_Expecter[K, E]) Read(ttx interface{}, id interface{}, opts ...interface{}) *RepositoryTx_Read_Call[K, E] {
	return &RepositoryTx_Read_Call[K, E]{Call: _e.mock.On("Read",
		append([]interface{}{ttx, id}, opts...)...)}
}

func (_c *RepositoryTx_Read_Call[K, E]) Run(run func(ttx sqlr.TTx, id K, opts ...func(qb *sqlr.QueryBuilderRead))) *RepositoryTx_Read_Call[K, E] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 sqlr.TTx
		if args[0] != nil {
			arg0 = args[0].(sqlr.TTx)
		}
		var arg1 K
		if args[1] != nil {
			arg1 = args[1].(K)
		}
		var arg2 []func(qb *sqlr.QueryBuilderRead)
		var variadicArgs []func(qb *sqlr.QueryBuilderRead)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(qb *sqlr.QueryBuilderRead))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *RepositoryTx_Read_Call[K, E]) Return(v *E, err error) *RepositoryTx_Read_Call[K, E] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *RepositoryTx_Read_Call[K, E]) RunAndReturn(run func(ttx sqlr.TTx, id K, opts ...func(qb *sqlr.QueryBuilderRead)) (*E, error)) *RepositoryTx_Read_Call[K, E] {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type RepositoryTx
func (_mock *RepositoryTx[K, E]) Update(ttx sqlr.TTx, entity *E, opts ...func(qb *sqlr.QueryBuilderUpdate)) (*E, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ttx, entity, opts)
	} else {
		tmpRet = _mock.Called(ttx, entity)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *E
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(sqlr.TTx, *E, ...func(qb *sqlr.QueryBuilderUpdate)) (*E, error)); ok {
		return returnFunc(ttx, entity, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(sqlr.TTx, *E, ...func(qb *sqlr.QueryBuilderUpdate)) *E); ok {
		r0 = returnFunc(ttx, entity, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*E)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(sqlr.TTx, *E, ...func(qb *sqlr.QueryBuilderUpdate)) error); ok {
		r1 = returnFunc(ttx, entity, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RepositoryTx_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type RepositoryTx_Update_Call[K sqlr.KeyTypes, E sqlr.Entitier[K]] struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ttx sqlr.TTx
//   - entity *E
//   - opts ...func(qb *sqlr.QueryBuilderUpdate)
func (_e *RepositoryTx_Expecter[K, E]) Update(ttx interface{}, entity interface{}, opts ...interface{}) *RepositoryTx_Update_Call[K, E] {
	return &RepositoryTx_Update_Call[K, E]{Call: _e.mock.On("Update",
		append([]interface{}{ttx, entity}, opts...)...)}
}

func (_c *RepositoryTx_Update_Call[K, E]) Run(run func(ttx sqlr.TTx, entity *E, opts ...func(qb *sqlr.QueryBuilderUpdate))) *RepositoryTx_Update_Call[K, E] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 sqlr.TTx
		if args[0] != nil {
			arg0 = args[0].(sqlr.TTx)
		}
		var arg1 *E
		if args[1] != nil {
			arg1 = args[1].(*E)
		}
		var arg2 []func(qb *sqlr.QueryBuilderUpdate)
		var variadicArgs []func(qb *sqlr.QueryBuilderUpdate)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(qb *sqlr.QueryBuilderUpdate))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *RepositoryTx_Update_Call[K, E]) Return(v *E, err error) *RepositoryTx_Update_Call[K, E] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *RepositoryTx_Update_Call[K, E]) RunAndReturn(run func(ttx sqlr.TTx, entity *E, opts ...func(qb *sqlr.QueryBuilderUpdate)) (*E, error)) *RepositoryTx_Update_Call[K, E] {
	_c.Call.Return(run)
	return _c
}
