// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sqlr

import (
	"context"

	"github.com/gosoline-project/sqlr"
	mock "github.com/stretchr/testify/mock"
)

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository[K sqlr.KeyTypes, E sqlr.Entitier[K]](t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository[K, E] {
	mock := &Repository[K, E]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Repository is an autogenerated mock type for the Repository type
type Repository[K sqlr.KeyTypes, E sqlr.Entitier[K]] struct {
	mock.Mock
}

type Repository_Expecter[K sqlr.KeyTypes, E sqlr.Entitier[K]] struct {
	mock *mock.Mock
}

func (_m *Repository[K, E]) EXPECT() *Repository_Expecter[K, E] {
	return &Repository_Expecter[K, E]{mock: &_m.Mock}
}

// Close provides a mock function for the type Repository
func (_mock *Repository[K, E]) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type Repository_Close_Call[K sqlr.KeyTypes, E sqlr.Entitier[K]] struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *Repository_Expecter[K, E]) Close() *Repository_Close_Call[K, E] {
	return &Repository_Close_Call[K, E]{Call: _e.mock.On("Close")}
}

func (_c *Repository_Close_Call[K, E]) Run(run func()) *Repository_Close_Call[K, E] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Repository_Close_Call[K, E]) Return(err error) *Repository_Close_Call[K, E] {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_Close_Call[K, E]) RunAndReturn(run func() error) *Repository_Close_Call[K, E] {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type Repository
func (_mock *Repository[K, E]) Create(ctx context.Context, entity *E, opts ...func(qb *sqlr.QueryBuilderCreate)) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, entity, opts)
	} else {
		tmpRet = _mock.Called(ctx, entity)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *E, ...func(qb *sqlr.QueryBuilderCreate)) error); ok {
		r0 = returnFunc(ctx, entity, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Repository_Create_Call[K sqlr.KeyTypes, E sqlr.Entitier[K]] struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *E
//   - opts ...func(qb *sqlr.QueryBuilderCreate)
func (_e *Repository_Expecter[K, E]) Create(ctx interface{}, entity interface{}, opts ...interface{}) *Repository_Create_Call[K, E] {
	return &Repository_Create_Call[K, E]{Call: _e.mock.On("Create",
		append([]interface{}{ctx, entity}, opts...)...)}
}

func (_c *Repository_Create_Call[K, E]) Run(run func(ctx context.Context, entity *E, opts ...func(qb *sqlr.QueryBuilderCreate))) *Repository_Create_Call[K, E] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *E
		if args[1] != nil {
			arg1 = args[1].(*E)
		}
		var arg2 []func(qb *sqlr.QueryBuilderCreate)
		var variadicArgs []func(qb *sqlr.QueryBuilderCreate)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(qb *sqlr.QueryBuilderCreate))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Repository_Create_Call[K, E]) Return(err error) *Repository_Create_Call[K, E] {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_Create_Call[K, E]) RunAndReturn(run func(ctx context.Context, entity *E, opts ...func(qb *sqlr.QueryBuilderCreate)) error) *Repository_Create_Call[K, E] {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type Repository
func (_mock *Repository[K, E]) Delete(ctx context.Context, id K, opts ...func(qb *sqlr.QueryBuilderDelete)) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, id, opts)
	} else {
		tmpRet = _mock.Called(ctx, id)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, K, ...func(qb *sqlr.QueryBuilderDelete)) error); ok {
		r0 = returnFunc(ctx, id, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Repository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Repository_Delete_Call[K sqlr.KeyTypes, E sqlr.Entitier[K]] struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id K
//   - opts ...func(qb *sqlr.QueryBuilderDelete)
func (_e *Repository_Expecter[K, E]) Delete(ctx interface{}, id interface{}, opts ...interface{}) *Repository_Delete_Call[K, E] {
	return &Repository_Delete_Call[K, E]{Call: _e.mock.On("Delete",
		append([]interface{}{ctx, id}, opts...)...)}
}

func (_c *Repository_Delete_Call[K, E]) Run(run func(ctx context.Context, id K, opts ...func(qb *sqlr.QueryBuilderDelete))) *Repository_Delete_Call[K, E] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 K
		if args[1] != nil {
			arg1 = args[1].(K)
		}
		var arg2 []func(qb *sqlr.QueryBuilderDelete)
		var variadicArgs []func(qb *sqlr.QueryBuilderDelete)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(qb *sqlr.QueryBuilderDelete))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Repository_Delete_Call[K, E]) Return(err error) *Repository_Delete_Call[K, E] {
	_c.Call.Return(err)
	return _c
}

func (_c *Repository_Delete_Call[K, E]) RunAndReturn(run func(ctx context.Context, id K, opts ...func(qb *sqlr.QueryBuilderDelete)) error) *Repository_Delete_Call[K, E] {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type Repository
func (_mock *Repository[K, E]) Query(ctx context.Context, opts ...func(qb *sqlr.QueryBuilderSelect)) ([]E, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, opts)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 []E
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...func(qb *sqlr.QueryBuilderSelect)) ([]E, error)); ok {
		return returnFunc(ctx, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...func(qb *sqlr.QueryBuilderSelect)) []E); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]E)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...func(qb *sqlr.QueryBuilderSelect)) error); ok {
		r1 = returnFunc(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type Repository_Query_Call[K sqlr.KeyTypes, E sqlr.Entitier[K]] struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...func(qb *sqlr.QueryBuilderSelect)
func (_e *Repository_Expecter[K, E]) Query(ctx interface{}, opts ...interface{}) *Repository_Query_Call[K, E] {
	return &Repository_Query_Call[K, E]{Call: _e.mock.On("Query",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *Repository_Query_Call[K, E]) Run(run func(ctx context.Context, opts ...func(qb *sqlr.QueryBuilderSelect))) *Repository_Query_Call[K, E] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []func(qb *sqlr.QueryBuilderSelect)
		var variadicArgs []func(qb *sqlr.QueryBuilderSelect)
		if len(args) > 1 {
			variadicArgs = args[1].([]func(qb *sqlr.QueryBuilderSelect))
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *Repository_Query_Call[K, E]) Return(vs []E, err error) *Repository_Query_Call[K, E] {
	_c.Call.Return(vs, err)
	return _c
}

func (_c *Repository_Query_Call[K, E]) RunAndReturn(run func(ctx context.Context, opts ...func(qb *sqlr.QueryBuilderSelect)) ([]E, error)) *Repository_Query_Call[K, E] {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function for the type Repository
func (_mock *Repository[K, E]) Read(ctx context.Context, id K, opts ...func(qb *sqlr.QueryBuilderRead)) (*E, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, id, opts)
	} else {
		tmpRet = _mock.Called(ctx, id)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 *E
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, K, ...func(qb *sqlr.QueryBuilderRead)) (*E, error)); ok {
		return returnFunc(ctx, id, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, K, ...func(qb *sqlr.QueryBuilderRead)) *E); ok {
		r0 = returnFunc(ctx, id, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*E)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, K, ...func(qb *sqlr.QueryBuilderRead)) error); ok {
		r1 = returnFunc(ctx, id, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type Repository_Read_Call[K sqlr.KeyTypes, E sqlr.Entitier[K]] struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx context.Context
//   - id K
//   - opts ...func(qb *sqlr.QueryBuilderRead)
func (_e *Repository_Expecter[K, E]) Read(ctx interface{}, id interface{}, opts ...interface{}) *Repository_Read_Call[K, E] {
	return &Repository_Read_Call[K, E]{Call: _e.mock.On("Read",
		append([]interface{}{ctx, id}, opts...)...)}
}

func (_c *Repository_Read_Call[K, E]) Run(run func(ctx context.Context, id K, opts ...func(qb *sqlr.QueryBuilderRead))) *Repository_Read_Call[K, E] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 K
		if args[1] != nil {
			arg1 = args[1].(K)
		}
		var arg2 []func(qb *sqlr.QueryBuilderRead)
		var variadicArgs []func(qb *sqlr.QueryBuilderRead)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(qb *sqlr.QueryBuilderRead))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Repository_Read_Call[K, E]) Return(v *E, err error) *Repository_Read_Call[K, E] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Repository_Read_Call[K, E]) RunAndReturn(run func(ctx context.Context, id K, opts ...func(qb *sqlr.QueryBuilderRead)) (*E, error)) *Repository_Read_Call[K, E] {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type Repository
func (_mock *Repository[K, E]) Update(ctx context.Context, entity *E, opts ...func(qb *sqlr.QueryBuilderUpdate)) (*E, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, entity, opts)
	} else {
		tmpRet = _mock.Called(ctx, entity)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *E
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *E, ...func(qb *sqlr.QueryBuilderUpdate)) (*E, error)); ok {
		return returnFunc(ctx, entity, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *E, ...func(qb *sqlr.QueryBuilderUpdate)) *E); ok {
		r0 = returnFunc(ctx, entity, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*E)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *E, ...func(qb *sqlr.QueryBuilderUpdate)) error); ok {
		r1 = returnFunc(ctx, entity, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Repository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Repository_Update_Call[K sqlr.KeyTypes, E sqlr.Entitier[K]] struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *E
//   - opts ...func(qb *sqlr.QueryBuilderUpdate)
func (_e *Repository_Expecter[K, E]) Update(ctx interface{}, entity interface{}, opts ...interface{}) *Repository_Update_Call[K, E] {
	return &Repository_Update_Call[K, E]{Call: _e.mock.On("Update",
		append([]interface{}{ctx, entity}, opts...)...)}
}

func (_c *Repository_Update_Call[K, E]) Run(run func(ctx context.Context, entity *E, opts ...func(qb *sqlr.QueryBuilderUpdate))) *Repository_Update_Call[K, E] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *E
		if args[1] != nil {
			arg1 = args[1].(*E)
		}
		var arg2 []func(qb *sqlr.QueryBuilderUpdate)
		var variadicArgs []func(qb *sqlr.QueryBuilderUpdate)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(qb *sqlr.QueryBuilderUpdate))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *Repository_Update_Call[K, E]) Return(v *E, err error) *Repository_Update_Call[K, E] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *Repository_Update_Call[K, E]) RunAndReturn(run func(ctx context.Context, entity *E, opts ...func(qb *sqlr.QueryBuilderUpdate)) (*E, error)) *Repository_Update_Call[K, E] {
	_c.Call.Return(run)
	return _c
}
