// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sqlr

import (
	"github.com/gosoline-project/sqlr"
	mock "github.com/stretchr/testify/mock"
)

// newSetIdAware creates a new instance of setIdAware. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newSetIdAware[K sqlr.KeyTypes](t interface {
	mock.TestingT
	Cleanup(func())
}) *setIdAware[K] {
	mock := &setIdAware[K]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// setIdAware is an autogenerated mock type for the setIdAware type
type setIdAware[K sqlr.KeyTypes] struct {
	mock.Mock
}

type setIdAware_Expecter[K sqlr.KeyTypes] struct {
	mock *mock.Mock
}

func (_m *setIdAware[K]) EXPECT() *setIdAware_Expecter[K] {
	return &setIdAware_Expecter[K]{mock: &_m.Mock}
}

// SetId provides a mock function for the type setIdAware
func (_mock *setIdAware[K]) SetId(v K) {
	_mock.Called(v)
	return
}

// setIdAware_SetId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetId'
type setIdAware_SetId_Call[K sqlr.KeyTypes] struct {
	*mock.Call
}

// SetId is a helper method to define mock.On call
//   - v K
func (_e *setIdAware_Expecter[K]) SetId(v interface{}) *setIdAware_SetId_Call[K] {
	return &setIdAware_SetId_Call[K]{Call: _e.mock.On("SetId", v)}
}

func (_c *setIdAware_SetId_Call[K]) Run(run func(v K)) *setIdAware_SetId_Call[K] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 K
		if args[0] != nil {
			arg0 = args[0].(K)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *setIdAware_SetId_Call[K]) Return() *setIdAware_SetId_Call[K] {
	_c.Call.Return()
	return _c
}

func (_c *setIdAware_SetId_Call[K]) RunAndReturn(run func(v K)) *setIdAware_SetId_Call[K] {
	_c.Run(run)
	return _c
}
