// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sqlr

import (
	mock "github.com/stretchr/testify/mock"
)

// NewTableNamer creates a new instance of TableNamer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTableNamer(t interface {
	mock.TestingT
	Cleanup(func())
}) *TableNamer {
	mock := &TableNamer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TableNamer is an autogenerated mock type for the TableNamer type
type TableNamer struct {
	mock.Mock
}

type TableNamer_Expecter struct {
	mock *mock.Mock
}

func (_m *TableNamer) EXPECT() *TableNamer_Expecter {
	return &TableNamer_Expecter{mock: &_m.Mock}
}

// TableName provides a mock function for the type TableNamer
func (_mock *TableNamer) TableName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TableName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// TableNamer_TableName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TableName'
type TableNamer_TableName_Call struct {
	*mock.Call
}

// TableName is a helper method to define mock.On call
func (_e *TableNamer_Expecter) TableName() *TableNamer_TableName_Call {
	return &TableNamer_TableName_Call{Call: _e.mock.On("TableName")}
}

func (_c *TableNamer_TableName_Call) Run(run func()) *TableNamer_TableName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TableNamer_TableName_Call) Return(s string) *TableNamer_TableName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *TableNamer_TableName_Call) RunAndReturn(run func() string) *TableNamer_TableName_Call {
	_c.Call.Return(run)
	return _c
}
